# Generated by Django 3.1.2 on 2020-11-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(help_text='项目id', max_length=10, null=True)),
                ('api_name', models.CharField(help_text='接口名称', max_length=100, null=True)),
                ('api_method', models.CharField(help_text='接口名称', max_length=100, null=True)),
                ('api_url', models.CharField(help_text='url', max_length=1000, null=True)),
                ('api_header', models.CharField(help_text='请求头', max_length=1000, null=True)),
                ('api_login', models.CharField(help_text='接口请求是否带登录状态', max_length=100, null=True)),
                ('api_host', models.CharField(help_text='域名', max_length=100, null=True)),
                ('api_description', models.CharField(help_text='接口描述', max_length=100, null=True)),
                ('api_body_method', models.CharField(help_text='请求体编码方式', max_length=20, null=True)),
                ('api_body', models.CharField(help_text='请求体', max_length=1000, null=True)),
                ('api_result', models.TextField(help_text='返回内容', null=True)),
                ('api_sign', models.CharField(help_text='是否需要验证签名', max_length=10, null=True)),
                ('file_key', models.CharField(help_text='文件key', max_length=50, null=True)),
                ('file_name', models.CharField(help_text='文件名', max_length=50, null=True)),
                ('public_header', models.CharField(help_text='全局公共请求头', max_length=1000, null=True)),
            ],
        ),
    ]
