# Generated by Django 3.1.2 on 2020-11-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_apis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='api_url',
            field=models.CharField(help_text='接口url', max_length=1000, null=True),
        ),
    ]
