# Generated by Django 3.1.2 on 2020-11-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_auto_20201103_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='api_method',
            field=models.CharField(help_text='接口请求方式', max_length=100, null=True),
        ),
    ]
